###Create User 
post http://localhost:3001/users/register
Content-Type: application/json

{
    "id": "12345678",
    "first_name": "Valery",
    "last_name": "Molina",
    "email": "valery.molina@correounivalle.edu.co",
    "phone": "318 234 5678",
    "available":"TRUE", 
    "user_password": "123456"
}

###Get all Users
get http://localhost:3001/users
Content-Type: application/json

###Change status of user
put http://localhost:3001/users/available
Content-Type: application/json

{
    "id": 123421233,
    "available":"TRUE"
}

### Edit user
put http://localhost:3001/users/edit/123421233
Content-Type: application/json

{
    "first_name": "José Gabriel",
    "last_name": "Jiménez Vidales",
    "email": "jose.gabriel@newemail.com",
    "phone": "123 456 7890",
    "available": true
}

###Login
post http://localhost:3001/users/login
Content-Type: application/json

{
    "email": "jose.vidales@correounivalle.edu.co", 
    "user_password": "123456"
}

###Get all movies
get http://localhost:3001/movies
Content-Type: application/json

###Get movie by id
get http://localhost:3001/movies/1
Content-Type: application/json

### add movie 
post http://localhost:3001/movies/add
Content-Type: application/json

{
    "title": "Baby girl",
    "synopsis": "A skilled thief is offered a chance to have his past crimes forgiven if he can successfully perform inception on a target's mind.",
    "rating": "PG-13",
    "image_url": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyrqht3oVnDQ4-rJBUdMbxTVTh3Zd0yJKwIw&s",
    "available":"TRUE", 
    "genre": "sci-fi",
    "administrator_id": 123456789
}


### edit movie 
put http://localhost:3001/movies/edit/3
Content-Type: application/json

{
    "title": "Inception 3",
    "synopsis": "A skilled thief is offered a chance to have his past crimes forgiven if he can successfully perform inception on a target's mind.",
    "rating": "PG-15",
    "available":"TRUE", 
    "genre": "sci-fi",
    "administrator_id": 123456789
}

###Add a movie function 
post http://localhost:3001/movie_function/add
Content-Type: application/json

{
  "movie_id": 1,
  "date_function": "2025-01-22",
  "time_function": "12:30:00",
  "room_number": 8,
  "available_seats": ["A1", "A2", "A3", "B1", "B2"]
}

###Get all dates movie functions
get http://localhost:3001/movie_function/movie/dates?movie_id=1
Content-Type: application/json


###Get all movie functions
get http://localhost:3001/movie_function/functions?movie_id=1&date_function=2025-01-21
Content-Type: application/json

###Buying cinema tickets 
post http://localhost:3001/invoice/buy-ticket
Content-Type: application/json

{
  "user_id": "12345678",
  "function_id": 3,
  "seats": ["A3"],
  "price_per_ticket": 10000
}

###Get all invoices
get http://localhost:3001/invoice
Content-Type: application/json